services:
  db:
    image: postgres:15
    container_name: database
    environment:
      POSTGRES_USER: architechs
      POSTGRES_PASSWORD: password_super_sicura
      POSTGRES_DB: coordinateDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-data.sql:/docker-entrypoint-initdb.d/init-data.sql
volumes:
  postgres_data:
