services:
  db:
    image: postgres:15
    container_name: database
    environment:
      POSTGRES_USER: architechs
      POSTGRES_PASSWORD: password_super_sicura
      POSTGRES_DB: coordinateDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-data.sql:/docker-entrypoint-initdb.d/init-data.sql

  app:
    build: .
    container_name: app-backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/coordinateDB
      SPRING_DATASOURCE_USERNAME: architechs
      SPRING_DATASOURCE_PASSWORD: password_super_sicura

volumes:
  postgres_data:
